// public/assets/react/src/components/Select.js
import React from 'react';

export default function Select({ label, options, value, onChange, name, optionLabel = 'descripcion', optionValue = 'id' }) {
  return (
    <label>
      {label}
      <select name={name} value={value} onChange={onChange}>
        <option value="">Seleccione...</option>
        {options.map(opt => (
          <option key={opt[optionValue]} value={opt[optionValue]}>
            {opt[optionLabel]}
          </option>
        ))}
      </select>
    </label>
  );
}

// assets/inertia-vue/src/components/Select.vue
<template>
  <label>
    {{ label }}
    <select :name="name" v-model="modelValue">
      <option value="">Seleccione...</option>
      <option v-for="opt in options" :key="opt[optionValue]" :value="opt[optionValue]">
        {{ opt[optionLabel] }}
      </option>
    </select>
  </label>
</template>

<script>
export default {
  props: {
    label: String,
    options: Array,
    name: String,
    modelValue: [String, Number],
    optionLabel: { type: String, default: 'descripcion' },
    optionValue: { type: String, default: 'id' }
  },
  emits: ['update:modelValue']
};
</script>
