// assets/inertia-react/Pages/NuevoCargoPlanilla.jsx
import React, { useMemo } from 'react';
import { useForm } from '@inertiajs/inertia-react';
import Select from '../components/Select';

export default function NuevoCargoPlanilla({
  areas,
  contratos,
  rubros,
  centrosCosto,
  ubicaciones,
  regiones,
  tarifas,
  cargoPlanillaId,
}) {
  const { data, setData, post } = useForm({
    areaSeleccionada: '',
    contratoSeleccionado: '',
    rubroSeleccionado: '',
    centroCostoSeleccionado: '',
    ubicacionSeleccionada: '',
    regionSeleccionada: '',
    tarifaSeleccionada: '',
    fechaCargoString: new Date().toISOString().slice(0, 10),
    cantidadUnidad: '',
    cantidadUnidadExtras: '',
  });

  // Filtrado de selects dependientes
  const rubroObj = useMemo(
    () => rubros.find(r => r.id === data.rubroSeleccionado),
    [data.rubroSeleccionado, rubros]
  );

  const centrosCostoFiltrados = useMemo(() => {
    if (rubroObj) {
      return centrosCosto.filter(c =>
        !rubroObj.centroCosto || c.id === rubroObj.centroCosto.id
      );
    }
    return centrosCosto;
  }, [rubroObj, centrosCosto]);

  const ubicacionesFiltradas = useMemo(() => {
    if (rubroObj) {
      return ubicaciones.filter(u =>
        !rubroObj.ubicacion || u.id === rubroObj.ubicacion.id
      );
    }
    return ubicaciones;
  }, [rubroObj, ubicaciones]);

  const regionesFiltradas = useMemo(() => {
    if (rubroObj) {
      return regiones.filter(r =>
        !rubroObj.region || r.id === rubroObj.region.id
      );
    }
    return regiones;
  }, [rubroObj, regiones]);

  const tarifasFiltradas = useMemo(() => {
    if (rubroObj) {
      return tarifas.filter(t => {
        if (!t.rubro) return true;
        if (!data.fechaCargoString) return t.rubro.id === rubroObj.id;
        const fechaCargo = new Date(data.fechaCargoString + ' 00:00:00');
        const fechaInicioTarifa = new Date(t.fechaInicio + ' 00:00:00');
        const fechaFinTarifa = new Date(t.fechaFin + ' 00:00:00');
        return t.rubro.id === rubroObj.id &&
          fechaInicioTarifa <= fechaCargo && fechaCargo <= fechaFinTarifa;
      });
    }
    return tarifas;
  }, [rubroObj, tarifas, data.fechaCargoString]);

  function handleChange(e) {
    setData(e.target.name, e.target.value);
  }

  function handleSelect(name, value) {
    setData(name, value);
    if (name === 'rubroSeleccionado') {
      const rubro = rubros.find(r => r.id === value);
      setData('centroCostoSeleccionado', rubro?.centroCosto?.id || '');
      setData('ubicacionSeleccionada', rubro?.ubicacion?.id || '');
      setData('regionSeleccionada', rubro?.region?.id || '');
      // Actualiza tarifa automáticamente
      const tarifa = tarifasFiltradas[0];
      setData('tarifaSeleccionada', tarifa ? tarifa.id : '');
    }
    if (name === 'fechaCargoString' && data.rubroSeleccionado) {
      // Actualiza tarifa si cambia la fecha
      const tarifa = tarifasFiltradas[0];
      setData('tarifaSeleccionada', tarifa ? tarifa.id : '');
    }
  }

  function submitForm(e) {
    e.preventDefault();
    post('/cargo-planilla');
  }

  return (
    <section className="box">
      <div className="header no-icon">
        <h3>{cargoPlanillaId ? 'Editar cargo de planilla' : 'Nuevo cargo de planilla'}</h3>
      </div>
      <form onSubmit={submitForm} className="block-content form">
        <fieldset>
          <legend>Datos generales</legend>
          <div className="form-group">
            <label htmlFor="fechaCargoString">Fecha:</label>
            <input
              type="date"
              name="fechaCargoString"
              value={data.fechaCargoString}
              onChange={e => handleSelect('fechaCargoString', e.target.value)}
              className="form-control"
            />
          </div>
          <div className="form-row">
            <Select
              label="Área:"
              name="areaSeleccionada"
              options={areas}
              value={data.areaSeleccionada}
              onChange={e => handleSelect('areaSeleccionada', e.target.value)}
              optionLabel="descripcion"
              optionValue="id"
            />
          </div>
          <div className="form-row">
            <Select
              label="Empleado:"
              name="contratoSeleccionado"
              options={contratos}
              value={data.contratoSeleccionado}
              onChange={e => handleSelect('contratoSeleccionado', e.target.value)}
              optionLabel="codigoNombreCompleto"
              optionValue="id"
            />
            <Select
              label="Rubro:"
              name="rubroSeleccionado"
              options={rubros}
              value={data.rubroSeleccionado}
              onChange={e => handleSelect('rubroSeleccionado', e.target.value)}
              optionLabel="abreviaturaNombre"
              optionValue="id"
            />
            <Select
              label="Cultivo (Centro de costo):"
              name="centroCostoSeleccionado"
              options={centrosCostoFiltrados}
              value={data.centroCostoSeleccionado}
              onChange={e => handleSelect('centroCostoSeleccionado', e.target.value)}
              optionLabel="abreviaturaCentroCosto"
              optionValue="id"
            />
            <Select
              label="Región mayor (Ubicación):"
              name="ubicacionSeleccionada"
              options={ubicacionesFiltradas}
              value={data.ubicacionSeleccionada}
              onChange={e => handleSelect('ubicacionSeleccionada', e.target.value)}
              optionLabel="abreviaturaUbicacion"
              optionValue="id"
            />
            {regiones.length > 0 && (
              <Select
                label="Región menor (región):"
                name="regionSeleccionada"
                options={regionesFiltradas}
                value={data.regionSeleccionada}
                onChange={e => handleSelect('regionSeleccionada', e.target.value)}
                optionLabel="idAbreviatura"
                optionValue="id"
              />
            )}
          </div>
          <div className="form-row">
            <div className="form-group">
              <label htmlFor="cantidad-unidad">Cantidad unidad:</label>
              <input
                type="number"
                name="cantidadUnidad"
                value={data.cantidadUnidad}
                onChange={handleChange}
                className="form-control"
              />
            </div>
            <div className="form-group">
              <label htmlFor="cantidad-unidad-extra">Cantidad unidad extraordinario:</label>
              <input
                type="number"
                name="cantidadUnidadExtras"
                value={data.cantidadUnidadExtras}
                onChange={handleChange}
                className="form-control"
              />
            </div>
          </div>
          <div className="form-group">
            <Select
              label="Tarifa:"
              name="tarifaSeleccionada"
              options={tarifasFiltradas}
              value={data.tarifaSeleccionada}
              onChange={e => handleSelect('tarifaSeleccionada', e.target.value)}
              optionLabel="nombre"
              optionValue="id"
            />
          </div>
        </fieldset>
        <button type="submit" className="btn">Guardar</button>
      </form>
    </section>
  );
}

// frontend/inertia-vue/src/NuevoCargoPlanilla.vue
<template>
  <section class="box">
    <div class="header no-icon">
      <h3>{{ cargoPlanillaId ? 'Editar cargo de planilla' : 'Nuevo cargo de planilla' }}</h3>
    </div>
    <form @submit.prevent="submitForm" class="block-content form">
      <div class="content with-actions">
        <fieldset>
          <legend>Datos generales</legend>
          <div class="form-group">
            <label for="fechaCargoString">Fecha:</label>
            <input type="date" v-model="form.fechaCargoString" id="fechaCargoString" class="form-control" @change="updateTarifa" />
          </div>
          <div class="form-row">
            <Select
              label="Área:"
              :options="areas"
              v-model="form.areaSeleccionada"
              option-label="descripcion"
              option-value="id"
            />
          </div>
          <div class="form-row">
            <Select
              label="Empleado:"
              :options="contratos"
              v-model="form.contratoSeleccionado"
              option-label="codigoNombreCompleto"
              option-value="id"
            />
            <Select
              label="Rubro:"
              :options="rubros"
              v-model="form.rubroSeleccionado"
              option-label="abreviaturaNombre"
              option-value="id"
              @change="onRubroChange"
            />
            <Select
              label="Cultivo (Centro de costo):"
              :options="centrosCostoFiltrados"
              v-model="form.centroCostoSeleccionado"
              option-label="abreviaturaCentroCosto"
              option-value="id"
            />
            <Select
              label="Región mayor (Ubicación):"
              :options="ubicacionesFiltradas"
              v-model="form.ubicacionSeleccionada"
              option-label="abreviaturaUbicacion"
              option-value="id"
            />
            <Select
              v-if="regiones.length > 0"
              label="Región menor (región):"
              :options="regionesFiltradas"
              v-model="form.regionSeleccionada"
              option-label="idAbreviatura"
              option-value="id"
            />
          </div>
          <div class="form-row">
            <div class="form-group">
              <label for="cantidad-unidad">Cantidad unidad:</label>
              <input type="number" v-model="form.cantidadUnidad" id="cantidad-unidad" class="form-control" />
            </div>
            <div class="form-group">
              <label for="cantidad-unidad-extra">Cantidad unidad extraordinario:</label>
              <input type="number" v-model="form.cantidadUnidadExtras" id="cantidad-unidad-extra" class="form-control" />
            </div>
          </div>
          <div class="form-group">
            <Select
              label="Tarifa:"
              :options="tarifasFiltradas"
              v-model="form.tarifaSeleccionada"
              option-label="nombre"
              option-value="id"
            />
          </div>
        </fieldset>
        <button type="submit" class="btn">Guardar</button>
      </div>
    </form>
  </section>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import { useForm } from '@inertiajs/vue3';
import Select from '../components/Select.vue'; // Usa el componente Select reutilizable

const props = defineProps({
  areas: Array,
  contratos: Array,
  rubros: Array,
  centrosCosto: Array,
  ubicaciones: Array,
  regiones: Array,
  tarifas: Array,
  cargoPlanillaId: [String, Number],
});

const form = useForm({
  areaSeleccionada: null,
  contratoSeleccionado: null,
  rubroSeleccionado: null,
  centroCostoSeleccionado: null,
  ubicacionSeleccionada: null,
  regionSeleccionada: null,
  tarifaSeleccionada: null,
  fechaCargoString: new Date().toISOString().slice(0, 10),
  cantidadUnidad: '',
  cantidadUnidadExtras: '',
});

const centrosCostoFiltrados = computed(() => {
  if (form.rubroSeleccionado) {
    return props.centrosCosto.filter(c =>
      !form.rubroSeleccionado.centroCosto || c.id === form.rubroSeleccionado.centroCosto.id
    );
  }
  return props.centrosCosto;
});

const ubicacionesFiltradas = computed(() => {
  if (form.rubroSeleccionado) {
    return props.ubicaciones.filter(u =>
      !form.rubroSeleccionado.ubicacion || u.id === form.rubroSeleccionado.ubicacion.id
    );
  }
  return props.ubicaciones;
});

const regionesFiltradas = computed(() => {
  if (form.rubroSeleccionado) {
    return props.regiones.filter(r =>
      !form.rubroSeleccionado.region || r.id === form.rubroSeleccionado.region.id
    );
  }
  return props.regiones;
});

const tarifasFiltradas = computed(() => {
  if (form.rubroSeleccionado) {
    return props.tarifas.filter(t => {
      if (!t.rubro) return true;
      if (!form.fechaCargoString) return t.rubro.id === form.rubroSeleccionado.id;
      const fechaCargo = new Date(form.fechaCargoString + ' 00:00:00');
      const fechaInicioTarifa = new Date(t.fechaInicio + ' 00:00:00');
      const fechaFinTarifa = new Date(t.fechaFin + ' 00:00:00');
      return t.rubro.id === form.rubroSeleccionado.id &&
        fechaInicioTarifa <= fechaCargo && fechaCargo <= fechaFinTarifa;
    });
  }
  return props.tarifas;
});

function onRubroChange() {
  form.centroCostoSeleccionado = form.rubroSeleccionado?.centroCosto?.id || null;
  form.ubicacionSeleccionada = form.rubroSeleccionado?.ubicacion?.id || null;
  form.regionSeleccionada = form.rubroSeleccionado?.region?.id || null;
  updateTarifa();
}

function updateTarifa() {
  if (form.rubroSeleccionado) {
    const tarifa = tarifasFiltradas.value[0];
    form.tarifaSeleccionada = tarifa ? tarifa.id : null;
  }
}

function submitForm() {
  form.post('/cargo-planilla');
}
</script>
