// frontend/inertia-react/src/NuevoCargoPlanilla.jsx
import { useForm } from '@inertiajs/react';

export default function NuevoCargoPlanilla({ areas, /* ... */ }) {
  const { data, setData, post } = useForm({
    areaSeleccionada: '',
    fechaCargoString: new Date().toISOString().slice(0, 10),
    // ...
  });

  function handleSubmit(e) {
    e.preventDefault();
    post('/cargo-planilla');
  }

  return (
    <form onSubmit={handleSubmit}>
      <label>Fecha:
        <input type="date" name="fechaCargoString" value={data.fechaCargoString} onChange={e => setData('fechaCargoString', e.target.value)} />
      </label>
      <label>Área:
        <select name="areaSeleccionada" value={data.areaSeleccionada} onChange={e => setData('areaSeleccionada', e.target.value)}>
          <option value="">Seleccione un área</option>
          {areas.map(a => <option key={a.id} value={a.id}>{a.descripcion}</option>)}
        </select>
      </label>
      {/* Repite para los demás campos */}
      <button type="submit">Guardar</button>
    </form>
  );
}

// frontend/inertia-vue/src/NuevoCargoPlanilla.vue
<template>
  <form @submit.prevent="handleSubmit">
    <label>Fecha:
      <input type="date" v-model="form.fechaCargoString" />
    </label>
    <label>Área:
      <select v-model="form.areaSeleccionada">
        <option value="">Seleccione un área</option>
        <option v-for="a in areas" :key="a.id" :value="a.id">{{ a.descripcion }}</option>
      </select>
    </label>
    <!-- Repite para los demás campos -->
    <button type="submit">Guardar</button>
  </form>
</template>

<script>
import { useForm } from '@inertiajs/vue3';

export default {
  props: ['areas' /*, ... */],
  setup(props) {
    const form = useForm({
      areaSeleccionada: '',
      fechaCargoString: new Date().toISOString().slice(0, 10),
      // ...
    });

    function handleSubmit() {
      form.post('/cargo-planilla');
    }

    return { form, areas: props.areas, handleSubmit };
  }
};
</script>
