// assets/vue/src/NuevoCargoPlanilla.vue
<template>
  <form @submit.prevent="handleSubmit">
    <label>Fecha:
      <input type="date" v-model="form.fechaCargoString" />
    </label>
    <Select
      label="Área:"
      :options="model.areas"
      v-model="form.areaSeleccionada"
    />
    <Select
      label="Empleado:"
      :options="model.contratos"
      v-model="form.contratoSeleccionado"
      option-label="codigoNombreCompleto"
      option-value="id"
    />
    <Select
      label="Rubro:"
      :options="model.rubros"
      v-model="form.rubroSeleccionado"
      option-label="abreviaturaNombre"
      option-value="id"
    />
    <Select
      label="Centro de costo:"
      :options="model.centrosCosto"
      v-model="form.centroCostoSeleccionado"
      option-label="abreviaturaCentroCosto"
      option-value="id"
    />
    <Select
      label="Ubicación:"
      :options="model.ubicaciones"
      v-model="form.ubicacionSeleccionada"
      option-label="abreviaturaUbicacion"
      option-value="id"
    />
    <Select
      label="Región:"
      :options="model.regiones"
      v-model="form.regionSeleccionada"
      option-label="idAbreviatura"
      option-value="id"
    />
    <Select
      label="Tarifa:"
      :options="model.tarifas"
      v-model="form.tarifaSeleccionada"
      option-label="nombre"
      option-value="id"
    />
    <label>Cantidad unidad:
      <input type="number" v-model="form.cantidadUnidad" />
    </label>
    <label>Cantidad unidad extraordinario:
      <input type="number" v-model="form.cantidadUnidadExtras" />
    </label>
    <button type="submit">Guardar</button>
  </form>
</template>

<script>
import Select from './components/Select.vue';

export default {
  components: { Select },
  data() {
    return {
      model: {
        areas: [],
        contratos: [],
        rubros: [],
        centrosCosto: [],
        ubicaciones: [],
        regiones: [],
        tarifas: [],
      },
      form: {
        areaSeleccionada: '',
        contratoSeleccionado: '',
        rubroSeleccionado: '',
        centroCostoSeleccionado: '',
        ubicacionSeleccionada: '',
        regionSeleccionada: '',
        tarifaSeleccionada: '',
        fechaCargoString: new Date().toISOString().slice(0, 10),
        cantidadUnidad: '',
        cantidadUnidadExtras: '',
      }
    };
  },
  mounted() {
    Promise.all([
      fetch('/api/areas').then(r => r.json()),
      fetch('/api/contratos').then(r => r.json()),
      fetch('/api/rubros').then(r => r.json()),
      fetch('/api/centros-costo').then(r => r.json()),
      fetch('/api/ubicaciones').then(r => r.json()),
      fetch('/api/regiones').then(r => r.json()),
      fetch('/api/tarifas').then(r => r.json()),
    ]).then(([areas, contratos, rubros, centrosCosto, ubicaciones, regiones, tarifas]) => {
      this.model.areas = areas;
      this.model.contratos = contratos;
      this.model.rubros = rubros;
      this.model.centrosCosto = centrosCosto;
      this.model.ubicaciones = ubicaciones;
      this.model.regiones = regiones;
      this.model.tarifas = tarifas;
    });
  },
  methods: {
    handleSubmit() {
      fetch('/api/cargo-planilla', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(this.form),
      }).then(r => r.json()).then(result => {
        alert(result.message);
      });
    }
  }
};
</script>

// frontend/react/src/NuevoCargoPlanilla.js
import React, { useEffect, useState } from 'react';
import Select from './components/Select';

export default function NuevoCargoPlanilla() {
  const [model, setModel] = useState({
    areas: [],
    contratos: [],
    rubros: [],
    centrosCosto: [],
    ubicaciones: [],
    regiones: [],
    tarifas: [],
  });
  const [form, setForm] = useState({
    areaSeleccionada: '',
    contratoSeleccionado: '',
    rubroSeleccionado: '',
    centroCostoSeleccionado: '',
    ubicacionSeleccionada: '',
    regionSeleccionada: '',
    tarifaSeleccionada: '',
    fechaCargoString: new Date().toISOString().slice(0, 10),
    cantidadUnidad: '',
    cantidadUnidadExtras: '',
  });

  useEffect(() => {
    Promise.all([
      fetch('/api/areas').then(r => r.json()),
      fetch('/api/contratos').then(r => r.json()),
      fetch('/api/rubros').then(r => r.json()),
      fetch('/api/centros-costo').then(r => r.json()),
      fetch('/api/ubicaciones').then(r => r.json()),
      fetch('/api/regiones').then(r => r.json()),
      fetch('/api/tarifas').then(r => r.json()),
    ]).then(([areas, contratos, rubros, centrosCosto, ubicaciones, regiones, tarifas]) => {
      setModel({ areas, contratos, rubros, centrosCosto, ubicaciones, regiones, tarifas });
    });
  }, []);

  function handleSelect(name, value) {
    setForm({ ...form, [name]: value });
  }

  function handleChange(e) {
    setForm({ ...form, [e.target.name]: e.target.value });
  }

  function handleSubmit(e) {
    e.preventDefault();
    fetch('/api/cargo-planilla', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form),
    }).then(r => r.json()).then(result => {
      alert(result.message);
    });
  }

  return (
    <form onSubmit={handleSubmit}>
      <label>Fecha:
        <input type="date" name="fechaCargoString" value={form.fechaCargoString} onChange={handleChange} />
      </label>
      <Select
        label="Área:"
        name="areaSeleccionada"
        options={model.areas}
        value={form.areaSeleccionada}
        onChange={e => handleSelect('areaSeleccionada', e.target.value)}
      />
      <Select
        label="Empleado:"
        name="contratoSeleccionado"
        options={model.contratos}
        value={form.contratoSeleccionado}
        onChange={e => handleSelect('contratoSeleccionado', e.target.value)}
        optionLabel="codigoNombreCompleto"
        optionValue="id"
      />
      <Select
        label="Rubro:"
        name="rubroSeleccionado"
        options={model.rubros}
        value={form.rubroSeleccionado}
        onChange={e => handleSelect('rubroSeleccionado', e.target.value)}
        optionLabel="abreviaturaNombre"
        optionValue="id"
      />
      <Select
        label="Centro de costo:"
        name="centroCostoSeleccionado"
        options={model.centrosCosto}
        value={form.centroCostoSeleccionado}
        onChange={e => handleSelect('centroCostoSeleccionado', e.target.value)}
        optionLabel="abreviaturaCentroCosto"
        optionValue="id"
      />
      <Select
        label="Ubicación:"
        name="ubicacionSeleccionada"
        options={model.ubicaciones}
        value={form.ubicacionSeleccionada}
        onChange={e => handleSelect('ubicacionSeleccionada', e.target.value)}
        optionLabel="abreviaturaUbicacion"
        optionValue="id"
      />
      <Select
        label="Región:"
        name="regionSeleccionada"
        options={model.regiones}
        value={form.regionSeleccionada}
        onChange={e => handleSelect('regionSeleccionada', e.target.value)}
        optionLabel="idAbreviatura"
        optionValue="id"
      />
      <Select
        label="Tarifa:"
        name="tarifaSeleccionada"
        options={model.tarifas}
        value={form.tarifaSeleccionada}
        onChange={e => handleSelect('tarifaSeleccionada', e.target.value)}
        optionLabel="nombre"
        optionValue="id"
      />
      <label>Cantidad unidad:
        <input type="number" name="cantidadUnidad" value={form.cantidadUnidad} onChange={handleChange} />
      </label>
      <label>Cantidad unidad extraordinario:
        <input type="number" name="cantidadUnidadExtras" value={form.cantidadUnidadExtras} onChange={handleChange} />
      </label>
      <button type="submit">Guardar</button>
    </form>
  );
}
